name: Release Charts Dev

on:
  pull_request:
    types: [closed]
    branches:
      - development
  workflow_run:
    workflows: ["Verify Chart Version"]
    types: [completed]

jobs:
  updateChartVersion:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development
      - name: Verify Chart Version
        run: |
        
          # Get the base commit SHA for the pull request
          # base_commit=$(jq .pull_request.base.sha -r "$GITHUB_EVENT_PATH")
          
          # Get the version number from Chart.yaml in the base commit
          git fetch &> /dev/null
          base_commit=$(git rev-parse HEAD)
          previous_version=$(git show $base_commit:charts/volumez-csi/Chart.yaml | grep '^version:' | awk '{print $2}')
          echo "previous version:" $previous_version
          
          if [[ $previous_version == *"rc"* ]]; then
            # Increment the RC version
            rc_version=$(echo $previous_version | awk -F '-rc.' '{print $2}')
            new_rc_version=$(expr $rc_version + 1)
            new_version=$(echo $previous_version | sed "s/rc.$rc_version/rc.$new_rc_version/")
            echo "new version1:" $new_version
          else
            # Increment the minor version
            minor_version=$(echo $previous_version | awk -F '.' '{print $2}')
            new_minor_version=$(expr $minor_version + 1)
            new_version=$(echo $previous_version | sed "s/.$minor_version./.$new_minor_version./")
            new_version="$new_version-rc.1"
          fi
          echo "new version3:" $new_version
          sed -i "0,/version:/s/version:.*/version: $new_version/" charts/volumez-csi/Chart.yaml
      
      - name: Commit changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -a -m "Update chart version to $new_version"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: development
          
  release:
    runs-on: ubuntu-latest
    needs: updateChartVersion
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: development
          fetch-depth: 0 

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git fetch 
      - name: Add repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n 1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
          
